### ISSUE TITLE
Nightlight is not being applied to the external monitor

### ISSUE THREAD

**Issue by btd1337** [elementary/wingpanel-indicator-nightlight#33]
Nightlight works correctly in primary monitor, but not works on external monitor.

PS: Switchboard-Plug-Display works just when external monitor isn't connected.

**Comment by danrabbit** [comment]
The indicator itself only interacts with gsettings, the component that controls which displays this effect is applied to is the Color plugin for the GNOME Settings Daemon with tracks its issues [here](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/issues)

Closing as "Out of scope" since the issue can't be fixed here and must be resolved in GSD
