### ISSUE TITLE
"nvidia x server settings" app disables night light

### ISSUE THREAD

**Issue by rythmkraze** [elementary/wingpanel-indicator-nightlight#35]
Opening the "nvidia x server settings" application disables night light. Restarting night light (say by snooze and un-snoozing) brings it back. But everytime you open  "nvidia x server settings" night light gets disabled.

**Comment by rythmkraze** [comment]
Driver Version: 390.48 (default in Juno)
GPU: GT 1030

**Comment by danrabbit** [comment]
The nightlight indicator just sets settings for the GSD nightlight plugin. You could file an issue against GSD here: https://gitlab.gnome.org/GNOME/gnome-settings-daemon

Closing as "Out of Scope" for this repo because it doesn't actually contain the code for the nightlight feature itself and so the issue can't be resolved here

**Comment by rythmkraze** [comment]
Thanks
