### ISSUE TITLE
Add a gradual transition to nightlight

### ISSUE THREAD

**Issue by Maccer1** [elementary/wingpanel-indicator-nightlight#36]
When it's early in the morning, nightlight turns off because the sunrise already happened but I feel like it's still too early to turn it off completely (the screen looks so blue).  Something similar happens in the evening..

So I think it would be great if you added a gradual transition (1 hour long or so) from the warm temperature to 6500K. If you need an example of what I mean you can check f.lux, it has a slow gradual transition that lasts 1 hour.

**Comment by danrabbit** [comment]
This repo only contains code that sets gsettings for nightlight. It doesn't contain any of the logic for the nightlight feature itself. I'm going to close this issue as "Out of Scope" since this issue can't be fixed in this code base.

Please consider opening an issue against GNOME Settings Daemon [on GitLab](https://gitlab.gnome.org/GNOME/gnome-settings-daemon)
